### ISSUE TITLE
track.dat only writing 1 line

### ISSUE THREAD

**Issue by jlestz** [DenSto/APC_524_Project#11]
track.dat file is only recording one line with the input file current as of commit 13e1c254.

**Comment by waterfollower** [comment]
what is nwrite and nTimesteps?

**Comment by jlestz** [comment]
1, 100

**Comment by waterfollower** [comment]
what is output_pCount?

**Comment by jlestz** [comment]
1 -- I'm using the input.txt as it is in the repo right now.

**Comment by waterfollower** [comment]
should be fixed now.
