### ISSUE TITLE
1 GB space limit on Adroit

### ISSUE THREAD

**Issue by jlestz** [DenSto/APC_524_Project#12]
Just so that everyone is aware, there is a 1GB storage limit on our user accounts on Adroit of 1GB. Our repo is currently about 786MB, so if we end up doing a large production run, we might run into this problem. It could lead to otherwise esoteric error messages.

**Comment by nmandell** [comment]
I think we should be able to run in /scratch, which is unlimited

**Comment by jlestz** [comment]
Super! I didn't even think to look for a scratch directory on adroit.
