### ISSUE TITLE
I/O feature request: different output times for particles and fields 

### ISSUE THREAD

**Issue by jlestz** [DenSto/APC_524_Project#14]
Currently it seems that test particle data is written out with the same frequency as full field data, which is much more expensive. Even 100 steps can create 200MB of field data for our current 32^3 grid with a single particle. 

Can we create at least two different step sizes for output? One for small data (test particle trajectories, particle distributions, maybe field *slices*), and one for large data (full fields)?

**Comment by waterfollower** [comment]
Now there are separate output step sizes.

**Comment by jlestz** [comment]
Excellent, thank you!
