### ISSUE TITLE
need separate input files for unit tests

### ISSUE THREAD

**Issue by nmandell** [DenSto/APC_524_Project#15]
Unit tests which currently read ../data/unitest/input.txt should be changed to use a separate test-specific input file that should live in test_data (see e.g. readinput_unittests.txt). This way tests will not break when ../data/unitest/input.txt is changed.

**Comment by aglasser17** [comment]
Done.

**Comment by nmandell** [comment]
In fact, values currently needed from input file should just be hard coded into the test. We shouldn't be reading an input file unless that's what we're testing (i.e. readinput_unittests)

**Comment by aglasser17** [comment]
Why?  Tests are forced to build on existing modules... If you had to locally replicate all of the code you depend upon, you would have to rewrite the entire code in your test...

Refactoring the code to avoid using the input reading functions seems like a waste.
