### ISSUE TITLE
MPI on a cube

### ISSUE THREAD

**Issue by DenSto** [DenSto/APC_524_Project#2]
So the issue Ian raised about the limited timestep we can use got me thinking... Right now we plan on domain decomposition in just one direction.  As I code up the particle boundaries I'm realizing that if one can decompose in one direction, it's a trivial extension to do it in _every_ dimension, at least for the particles. I haven't given it much thought about the fields, though.  For anybody who's worked on the grid, what do you think? Has anybody been working on the grid boundary conditions?

**Comment by jlestz** [comment]
We considered this in one of the early meetings. I think our conclusions were that while the the decomposition is not difficult, it opens up the possibility for many new errors, and will make debugging much more difficult than a 1D decomposition. Just as an example, particles could cross multiple MPI domains in a single time step, which requires more careful handling than crossing a single domain. 

My vote is to have 3D decomposition be one of the prioritized stretch goals for beta. But we should get all features working and validate some physics cases with 1D decomposition before tackling this.

**Comment by DenSto** [comment]
Actually I thought about it, and particles crossing multiple is actually not a problem at all (I can show how to trivially address this).

If the grids can do this easily, I don't see why not.  I think I'll be easier to do the general case now, then do the specific case and _then_ try to generalize.
