### ISSUE TITLE
An issue with particle boundaries in the case of Poisson field initialization

### ISSUE THREAD

**Issue by aglasser17** [DenSto/APC_524_Project#20]
When "poisson" initialization is turned on, the call at particles/particle_handler.cpp:270:

int inc = boundaries_[i]->computeParticleBCs(&parts_);

hangs.

**Comment by DenSto** [comment]
Who put those while loops in there?

**Comment by aglasser17** [comment]
In where?

**Comment by DenSto** [comment]
In the particle boundaries, specifically the periodic ones. They're broken now.

**Comment by aglasser17** [comment]
I think if I set the cells large enough now, we can initialize the code with Poisson initialization.  When I ran it with small cells, the new assert particle boundary check:

virtual int BC_P_Periodic::particle_BC(Particle*): Assertion `newP.x[dim_index_] >= xMin_' failed.

triggered.  So that's good too.

**Comment by jlestz** [comment]
What is xMin_? If this is a constraint on box size that can be run, we need to make the user aware of what that limit is, preferably both as comment in the input file and also output an error to console that tells them how they can run similar case with adjusted dx.

**Comment by aglasser17** [comment]
Recall that as described in the other issue (about depositJ causing large velocities), we need cell size

dx > 4*pi*N

assuming uniform distribution, in order to resolve the plasma frequency.

**Comment by aglasser17** [comment]
(Sorry, where N is the # of particles in each cell.)

**Comment by aglasser17** [comment]
Since boundary conditions have been updated a great deal since this issue was opened, and since we are no longer experiencing problems, I am closing this issue.
