### ISSUE TITLE
Large number of particles leads to segfault after several steps

### ISSUE THREAD

**Issue by jlestz** [DenSto/APC_524_Project#26]
This was for 1 million particles, grid size of 16^3, MPI decomposition 4,4,4, physical size 1,1,1.

**Comment by jlestz** [comment]
Same issue with 1000 particles, except no segfault for 6500 steps.

**Comment by aglasser17** [comment]
Was this true even with constField initialization?

**Comment by DenSto** [comment]
Does this only happen on mpi?

**Comment by DenSto** [comment]
I have a suspicion that this is the MPI analog to the particle blow-out problem. I've added some asserts to the MPI particle boundary condition, as well as getCellID. This may at least catch the problem. If not, it's something else.

**Comment by jlestz** [comment]
@aglasser17: this was with constant field initialization only. Did not try with Poisson. 

@DenSto: I can only create it in MPI for now (possibly just waiting long enough in serial would also cause the problem, but this takes too long with many particles)

**Comment by DenSto** [comment]
You could try it with the asserts I added. Also, have you tried it with chargeless particles? If that were still the case, that'd be a problem.

**Comment by nmandell** [comment]
Could it be some kind of memory leak? Where memory is being allocated but not freed during the course of the simulation and eventually causes a crash?

**Comment by DenSto** [comment]
Could be too, but it should be quick to at least single out if it's the EM fields or not with chargeless particles.

**Comment by DenSto** [comment]
Definitely some bugs with how the particles are being passed around by MPI. Will try to fix.

**Comment by jlestz** [comment]
Thanks, Denis.

**Comment by DenSto** [comment]
Found the problem. Apparently cells that should be receiving from right think they're receiving from the left (and vice versa). Yuan, if you ported my particle MPI code over to the fields, you'll probably be experiencing the same problem. There is a solution, but it'll require some thought.

**Comment by waterfollower** [comment]
@DenSto Thanks! I am looking into it right now.

**Comment by DenSto** [comment]
Pushed some changes. Particle passing might be correct now. Yuan, I'm less sure if it'll affect the fields, since it really only had to do with incrementing the box size.

**Comment by waterfollower** [comment]
what do you mean by "incrementing the box size"?

**Comment by DenSto** [comment]
Sorry. I'm running on little sleep right now. I mean adjusting the position of a particle to ensure it stays in the domain (i.e. wrapping around or pacmaning it's position)

**Comment by aglasser17** [comment]
This segfault is no longer occurring.
