### ISSUE TITLE
need to make sure all unit tests working

### ISSUE THREAD

**Issue by nmandell** [DenSto/APC_524_Project#27]
Currently many of the tests do not compile because of recent interface changes. For example, some grid tests cannot compile because the updatePeriodicGhostCells function was deprecated.

**Comment by waterfollower** [comment]
updatePeriodicGhostCells is no longer used

**Comment by nmandell** [comment]
I understand that, but some of the unit tests still call it. So the unit tests need to be changed to use the new function that replaces updatePeriodicGhostCells.

**Comment by nmandell** [comment]
Update: 
All tests now compile, but the following grid-related tests fail:
GridGetNumberOfCellsTest.returnsCorrectNumberOfCells
OGridTest.getCellIDReturnsInternalCells
OGridTest.getCellIDReturnsGhostCells
GridPrivateTest.periodicUpdateTest
GridPrivateTest.ghostVecSizeTest

**Comment by waterfollower** [comment]
I am fixing them

**Comment by nmandell** [comment]
Thanks!

**Comment by waterfollower** [comment]
All tests fixed!

**Comment by nmandell** [comment]
Excellent! I’m going to try to see if I can get the tests running in parallel real quick…
