### ISSUE TITLE
Error when nCell != [a a a] for some a

### ISSUE THREAD

**Issue by aglasser17** [DenSto/APC_524_Project#28]
nCell = [ 100, 32, 32 ] in the input file leads to an error:

EMOOPIC: grid/spookyGrid.cpp:325: void Grid::sliceMatToVec_(int, int, int, double*): Assertion `dex < nyTot_' failed.

**Comment by aglasser17** [comment]
Update: An input of [33,32,32] is fine, but [34,32,32] fails.

**Comment by waterfollower** [comment]
just fixed it. Try again

**Comment by aglasser17** [comment]
Still causing an error with [34,32,32]

**Comment by waterfollower** [comment]
did you pull the recent version? I tried this input and there is no error

**Comment by nmandell** [comment]
Also be sure to make clean after pulling

**Comment by aglasser17** [comment]
All good!
