### ISSUE TITLE
Particle sorting

### ISSUE THREAD

**Issue by DenSto** [DenSto/APC_524_Project#30]
Particle sorting, while in the code, is not being called and has not been tested.  Does anybody want to add a cadence to the input file, and I can test and see how it performs?

**Comment by nmandell** [comment]
Sure. It will be called input_info->nsort ?

**Comment by nmandell** [comment]
Make that nstep_sort

**Comment by DenSto** [comment]
Perfect. Already tested sorting; doesn't seem to break the code or anything.
