### ISSUE TITLE
Compilation error for google test

### ISSUE THREAD

**Issue by iochs** [DenSto/APC_524_Project#4]
@jlestz I get this error when I try to compile linking to google test:

Undefined symbols for architecture x86_64:
  "double* std::__1::copy<double const*, double*>(double const*, double const*, double*)", referenced from:
      Grid::setGhostVecAlt(int, double const*) in spookyGrid.o
  "double* std::__1::copy<double*, double*>(double*, double*, double*)", referenced from:
      Grid::getGhostVecAlt(int, double*) in spookyGrid.o
ld: symbol(s) not found for architecture x86_64

It is caused by your use of std::copy. Are you sure you aren't using anything deprecated in there?

**Comment by iochs** [comment]
I can get this all to compile and link if I use libstdc++ instead of libc++, but this is deprecated. So I think there might be an updated version of copy to link to?

**Comment by jlestz** [comment]
Resolved by including <algorithm>. No longer needs libstdc++.
