### ISSUE TITLE
how many number of particles do we start with?

### ISSUE THREAD

**Issue by DenSto** [DenSto/APC_524_Project#6]
I see in IO.hpp has both an np and a dens for the density. However, it also has Lxyz of the domain.  Then some combination of these are redundant, right? We should choose one. Should we use dens, or np, and if np, is it number of particles per domain, or per grid cell?

**Comment by nmandell** [comment]
You’re right… I don’t think we need dens. Whether np is per domain or per cell, I’m not sure. How is this usually specified in PIC codes?

**Comment by DenSto** [comment]
It's usually done with particles per cell. Either way though, I'm going to be just spreading them out uniformly over the domain, so at best it'll be an average particle per cell (that's what happens in a few timesteps anyway).

I'll take it to be ppc for now.

**Comment by DenSto** [comment]
Also, we need a mass ratio in the input.

**Comment by waterfollower** [comment]
I think we input averaged particle per cell is a good idea. By the way, dens was some dummy variable I put in for testing purpose. Feel free to remove it.

On Dec 14, 2016, at 22:04, DenSto <notifications@github.com<mailto:notifications@github.com>> wrote:


It's usually done with particles per cell. Either way though, I'm going to be just spreading them out uniformly over the domain, so at best it'll be an average particle per cell (that's what happens in a few timesteps anyway).

I'll take it to be ppc for now.
