### ISSUE TITLE
self consistency of boundary conditions

### ISSUE THREAD

**Issue by waterfollower** [DenSto/APC_524_Project#8]
I think the boundary conditions now may be over-specified, because the boundary conditions should be self consistent. For example, it doesn't make sense that x left boundary is periodic while x right boundary is not. Similarly, it doesn't make sense that field boundary is periodic while particle boundary is not.

**Comment by DenSto** [comment]
I mean we need the freedom to specify any specific boundary (i.e. field might be insulating/conducting while particle may be absorbing/reflecting), so they're not overspecified.
 
However, you're right that only certain combinations of boundaries make sense. Checking any combination for consistency may be a lot of work though. If you're up for it though go ahead.

**Comment by waterfollower** [comment]
You are right that we need the freedom. So we need some routine to check combinations.
Once we have the field boundary conditions implemented, I can write the check routine.

**Comment by DenSto** [comment]
Actually, the only case we really need to check is if either left or right are periodic, then they both are. That should be simple, right?

**Comment by waterfollower** [comment]
Seems to be.

**Comment by DenSto** [comment]
I guess you'll also need to check again the fields too, but then again if you do the above check, the similar check for fields, then make sure if one set is periodic then all are, that'll be enough.
