### ISSUE TITLE
Segfault while running code in serial

### ISSUE THREAD

**Issue by DenSto** [DenSto/APC_524_Project#9]
I'm getting a seg-fault at line 82 in oGrid.cpp. Does anybody know the cause?

**Comment by DenSto** [comment]
Found culprit, the calculation of iz, iy, and ix are not correct (problem appears throughout the file).

**Comment by DenSto** [comment]
Nevermind, fixed it.

**Comment by iochs** [comment]
Was this the cell Id snafu? Sorry about that was going to get to internal unit tests today.

Sent from my iPhone

On Dec 20, 2016, at 8:24 PM, DenSto <notifications@github.com<mailto:notifications@github.com>> wrote:


Nevermind, fixed it.
